In [19]:
import pandas as pd

# Đọc file
df_tuyen = pd.read_excel("giao_thong_data.xlsx", sheet_name="TuyenDuong")
df_doan = pd.read_excel("giao_thong_data.xlsx", sheet_name="DoanTuyen")
df_cap_ql = pd.read_excel("giao_thong_data.xlsx", sheet_name="CapQuanLy")
df_cap_duong = pd.read_excel("giao_thong_data.xlsx", sheet_name="CapDuong")

In [20]:

# Rename bảng tuyến
df_tuyen = df_tuyen.rename(columns={
    'Mã tuyến': 'Ma_tuyen',
    'Cấp quản lý': 'Cap_quan_ly'
})
df_tuyen

,Ma_tuyen,Tên tuyến,Cap_quan_ly,CD quản lý (km),CD thực tế (km),Đơn vị quản lý,Điểm đầu,Điểm cuối,Lat đầu,Lng đầu,Lat cuối,Lng cuối,Năm xây dựng,Năm hoàn thành,Ghi chú
0,QL4,Quốc lộ 4,QL,96.400,96.400,UBND tỉnh Lào Cai,Giao QL.4D (Xã Mường Khương),Giáp tỉnh Tuyên Quang (xã Tả Củ Tỷ),NaN,NaN,NaN,NaN,2014.0,NaN,NaN
1,QL4D,Quốc lộ 4D,QL,103.100,103.100,UBND tỉnh Lào Cai,Giáp tỉnh Lai Châu (Phường Sa Pa),Cửa khẩu Sín Tẻn (xã Mường Khương),NaN,NaN,NaN,NaN,2015.0,NaN,NaN
2,QL4E,Quốc lộ 4E,QL,134.060,134.060,UBND tỉnh Lào Cai,Giao QL.4 (xã Lùng Phình),Cột cờ Lũng Pô (xã A Mú Sung),NaN,NaN,NaN,NaN,2016.0,NaN,NaN
3,QL279,Quốc lộ 279,QL,121.500,121.500,UBND tỉnh Lào Cai,Giáp tỉnh Tuyên Quang (xã Nghĩa Đô),Giáp tỉnh Lai Châu (xã Nậm Xé),NaN,NaN,NaN,NaN,2012.0,NaN,NaN
4,QL37,Quốc lộ 37,QL,94.100,94.100,UBND tỉnh Lào Cai,Giáp tỉnh Phú Thọ (xã Thác Bà),Giáp tỉnh Sơn La (xã Thượng Bằng La),NaN,NaN,NaN,NaN,2017.0,NaN,NaN
5,QL70,Quốc lộ 70,QL,174.050,174.050,UBND tỉnh Lào Cai,Giáp tỉnh Phú Thọ (xã Yên Bình),Cửa khẩu Quốc tế,NaN,NaN,NaN,NaN,2009.0,NaN,NaN
6,QL32C,Quốc lộ 32C,QL,17.500,17.500,UBND tỉnh Lào Cai,Giáp tỉnh Phú Thọ (phường Âu Lâu),Giao QL.37 (phường Âu Lâu),NaN,NaN,NaN,NaN,2001.0,NaN,NaN
7,QL2D,Quốc lộ 2D,QL,27.600,27.600,UBND tỉnh Lào Cai,Giáp tỉnh Phú Thọ (phường Âu Lâu),Giao QL.37 (xã Thác Bà),NaN,NaN,NaN,NaN,2016.0,NaN,NaN
8,QL32,Quốc lộ 32,QL,175.004,175.004,UBND tỉnh Lào Cai,Giáp tỉnh Phú Thọ (xã Nghĩa Tâm),Giáp tỉnh Lai Châu (xã Khao Mang),NaN,NaN,NaN,NaN,2012.0,NaN,NaN
9,DT151,Đường tỉnh 151,DT,39.800,39.800,UBND tỉnh Lào Cai,Giao QL.4E (xã Gia Phú),"Giao QL,279 (xã Văn Bàn)",NaN,NaN,NaN,NaN,2023.0,NaN,NaN
10,DT151B,Đường tỉnh 151B,DT,50.600,50.600,UBND tỉnh Lào Cai,Giao ĐT.151 (xã Võ Lao),Xã Phong Dụ Hạ,NaN,NaN,NaN,NaN,2015.0,NaN,NaN
11,DT151C,Đường tỉnh 151C,DT,37.600,37.600,UBND tỉnh Lào Cai,Giao QL.4E (xã Bảo Thắng),Đấu nối vào điểm cuối ĐT.163 (xã Châu Quế),NaN,NaN,NaN,NaN,2018.0,NaN,NaN
12,DT152,Đường tỉnh 152,DT,68.501,68.501,UBND tỉnh Lào Cai,Giao QL.4D (phường Sa Pa),Giao QL.4E (xã Bảo Thắng),NaN,NaN,NaN,NaN,2015.0,NaN,NaN
13,DT152B,Đường tỉnh 152B,DT,55.000,55.000,UBND tỉnh Lào Cai,Giao ĐT.152 (xã Bản Hồ),Giao QL.279 (xã Dương Quỳ),NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,DT153,Đường tỉnh 153,DT,66.300,66.300,UBND tỉnh Lào Cai,Giao ĐT.154 (xã Bảo Nhai),Giao QL.279 (xã Nghĩa Đô),NaN,NaN,NaN,NaN,2013.0,NaN,NaN
15,DT154,Đường tỉnh 154,DT,109.000,109.000,UBND tỉnh Lào Cai,Giao QL.70 (Phường Lào Cai),Giao QL.70 (xã Xuân Quang),NaN,NaN,NaN,NaN,2010.0,NaN,NaN
16,DT155,Đường tỉnh 155,DT,73.000,73.000,UBND tỉnh Lào Cai,Giao ĐT.158 (xã Dền Sáng),Giao QL.4D (xã Cốc San),NaN,NaN,NaN,NaN,2010.0,NaN,NaN
17,DT156,Đường tỉnh 156,DT,58.000,58.000,UBND tỉnh Lào Cai,Xã Quang Kim,Giao ĐT.158 (xã Y Tý),NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,DT156B,Đường tỉnh 156B,DT,18.400,18.400,UBND tỉnh Lào Cai,Cửa khẩu Bản Vược,Giao ĐT.155 (xã Dền Sáng),NaN,NaN,NaN,NaN,2025.0,NaN,NaN
19,DT157,Đường tỉnh 157,DT,56.440,56.440,UBND tỉnh Lào Cai,Giao QL.4E (Phường Lào Cai),Giao QL.70 (xã Xuân Quang),NaN,NaN,NaN,NaN,2012.0,NaN,NaN
20,DT158,Đường tỉnh 158,DT,71.200,71.200,UBND tỉnh Lào Cai,Giao QL.4E (xã A Mú Sung),Giáp tỉnh Lai Châu (xã Dền Sáng),NaN,NaN,NaN,NaN,2010.0,NaN,NaN
21,DT159,Đường tỉnh 159,DT,79.200,79.200,UBND tỉnh Lào Cai,Cửa khẩu Hóa Chư Phùng (xã Si Ma Cai),Giao ĐT.153 (xã Bản Liền),NaN,NaN,NaN,NaN,2013.0,NaN,NaN
22,DT160,Đường tỉnh 160,DT,106.430,106.430,UBND tỉnh Lào Cai,Giao QL.4E (phường Cam Đường),Xã Tân Lĩnh,NaN,NaN,NaN,NaN,2013.0,NaN,NaN
23,DT161,Đường tỉnh 161,DT,63.420,63.420,UBND tỉnh Lào Cai,Giao QL.4E (phường Cam Đường),Đấu nối ĐT.164 (xã Lâm Giang),NaN,NaN,NaN,NaN,2023.0,NaN,NaN
24,DT162,Đường tỉnh 162,DT,37.876,37.876,UBND tỉnh Lào Cai,Giao QL.279 (xã Văn Bàn),Giao ĐT.151C (xã Bảo Thắng),NaN,NaN,NaN,NaN,2020.0,NaN,NaN
25,DT163,Đường tỉnh 163,DT,85.000,85.000,UBND tỉnh Lào Cai,Giao QL.37 (phường Yên Bái),Đấu nối ĐT.151C (xã Bảo Hà),NaN,NaN,NaN,NaN,2015.0,NaN,NaN
26,DT164,Đường tỉnh 164,DT,20.500,20.500,UBND tỉnh Lào Cai,Giao ĐT.163 (xã Đông Cuông),Đấu nối ĐT.161 (xã Bảo Hà),NaN,NaN,NaN,NaN,2015.0,NaN,NaN
27,DT165,Đường tỉnh 165,DT,18.000,18.000,UBND tỉnh Lào Cai,Giao ĐT.163 (xã Mậu A),Giao QL.70 (xã Bảo Ái),NaN,NaN,NaN,NaN,2021.0,NaN,NaN
28,DT166,Đường tỉnh 166,DT,52.000,52.000,UBND tỉnh Lào Cai,Giao QL.37 (phường Âu Lâu),Giao ĐT.163 (xã Đông Cuông),NaN,NaN,NaN,NaN,2018.0,NaN,NaN
29,DT170,Đường tỉnh 170,DT,79.400,79.400,UBND tỉnh Lào Cai,Giao ĐT.171 (xã Lục Yên),Giao QL.37 (xã Thác Bà),NaN,NaN,NaN,NaN,2015.0,NaN,NaN
30,DT171,Đường tỉnh 171,DT,27.000,27.000,UBND tỉnh Lào Cai,Giao QL.70 (xã Khánh Hòa),Giáp tỉnh Tuyên Quang (xã Lục Yên),NaN,NaN,NaN,NaN,2011.0,NaN,NaN
31,DT172,Đường tỉnh 172,DT,34.000,34.000,UBND tỉnh Lào Cai,Giao QL.37 (phường Âu Lâu),Giao QL.37 (xã Chấn Thịnh),NaN,NaN,NaN,NaN,2017.0,NaN,NaN
32,DT173,Đường tỉnh 173,DT,26.000,26.000,UBND tỉnh Lào Cai,Giao ĐT.172 (xã Chấn Thịnh),Giao QL.32 xã Nghĩa Tâm,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,DT174,Đường tỉnh 174,DT,33.000,33.000,UBND tỉnh Lào Cai,Giao QL.32 (Phường Trung Tâm),Xã Hạnh Phúc,NaN,NaN,NaN,NaN,2016.0,NaN,NaN
34,DT175,Đường tỉnh 175,DT,52.000,52.000,UBND tỉnh Lào Cai,Giao ĐT.166 (xã Mậu A),Giao QL.32 xã Liên Sơn,NaN,NaN,NaN,NaN,2018.0,NaN,NaN
35,DT175B,Đường tỉnh 175B,DT,19.500,19.500,UBND tỉnh Lào Cai,Giao QL.32 xã Púng Luông,Xã Púng Luông (giáp tỉnh Sơn La),NaN,NaN,NaN,NaN,2013.0,NaN,NaN
36,DX01,Đường Trạm Tấu - Bắc Yên,DX,16.000,16.000,NaN,Giao ĐT.174 (xã Hạnh Phúc),Xã Hạnh Phúc (giáp tỉnh Sơn La),NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,DX02,Đường Văn Chấn - Yên Lập,DX,17.089,17.089,NaN,Giao ĐT.173 (xã Chấn Thịnh),xã Chấn Thịnh (giáp tỉnh Phú Thọ),NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,DX03,Đường Sơn Thịnh - Suối Giàng,DX,11.300,11.300,NaN,Giao QL.32 (xã Văn Chấn),Xã Văn Chấn,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,DX04,Cầu và Đường Hai Đầu Cầu Cổ Phúc,DX,2.220,2.220,NaN,Xã Quy Mông,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,DX05,Đường Minh Bảo- Đại Đồng,DX,8.000,8.000,NaN,Phường Nam Cường,Phường Nam Cường,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,DX06,Đường Nguyễn Tất Thành,DX,5.600,5.600,NaN,Phường Yên Bái,Xã Yên Bình,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,DX07,Đường Âu Cơ,DX,10.970,10.970,NaN,Phường Yên Bái,IC12 (phường Âu Lâu),NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,DX08,Đường Nút giao IC12-Vân Hội,DX,7.300,7.300,NaN,IC12 (phường Âu Lâu),Xã Việt Hồng,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,DX09,Cầu và Đường hai đầu cầu Bách Lẫm,DX,1.900,1.900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,DX10,Cầu và Đường hai đầu cầu Tuần Quán,DX,4.100,4.100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,DX11,Đường nối QL.32C với IC12 và các nhánh rẽ,DX,15.300,15.300,NaN,Giao QL.32C (phường Âu Lâu),IC12 (phường Âu Lâu),NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,DX12,Đường nối QL.32 với ĐT.174,DX,49.117,49.117,NaN,Giao QL.32 (xã Văn Chấn),Giao ĐT.174 (xã Hạnh Phúc),NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,DX13,Đường gom đường cao tốc Nội Bài - Lào Cai,DX,7.510,7.510,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
# Rename bảng đoạn
df_doan = df_doan.rename(columns={
    'Mã tuyến': 'Ma_tuyen',
    'Cấp đường': 'Cap_duong',
    'CD thực tế (km)': 'chieu_dai_thuc_te',
    'Lý trình đầu (km)': 'ly_trinh_dau',
    'Lý trình cuối (km)': 'ly_trinh_cuoi'
})
df_doan.head

<bound method NDFrame.head of      Mã đoạn Ma_tuyen Cap_duong  ly_trinh_dau  ly_trinh_cuoi Tình trạng  \
0     QL4-01      QL4        IV         190.0        194.000        Tốt
1     QL4-02      QL4         V         194.0        250.800        Tốt
2     QL4-03      QL4         V         250.8        255.000        Tốt
3     QL4-04      QL4         V         255.0        272.000        Tốt
4     QL4-05      QL4         V         272.0        286.400        Tốt
..       ...      ...       ...           ...            ...        ...
202  DX11-02     DX11       III           7.6         12.200        NaN
203  DX11-03     DX11       III           0.0          2.000        NaN
204  DX11-04     DX11       III           0.0          2.030        NaN
205  DX12-01     DX12        IV           0.0         49.117        NaN
206  DX13-01     DX13       NaN           0.0          7.510        NaN

     chieu_dai_thuc_te Mã kết cấu mặt  Rộng mặt min (m)  Rộng mặt max (m)  \
0                 4.00            BTN              10.5              10.5
1                56.80            BTN               6.5               7.5
2                 4.20            BTN               5.0               5.0
3                17.00            BTN               6.5               7.5
4                14.40             LN               6.5               6.5
..                 ...            ...               ...               ...
202               4.60            NaN              21.0              21.0
203               2.00            NaN              21.0              21.0
204               2.00            NaN              21.0              21.0
205              45.81            NaN               5.0               5.0
206               7.51            NaN               5.5               7.0

     Rộng nền min (m)  Rộng nền max (m) Đơn vị bảo dưỡng  \
0                 NaN               NaN        Công ty …
1                 NaN               NaN              NaN
2                 NaN               NaN              NaN
3                 NaN               NaN              NaN
4                 NaN               NaN              NaN
..                ...               ...              ...
202               NaN               NaN              NaN
203               NaN               NaN              NaN
204               NaN               NaN              NaN
205               NaN               NaN              NaN
206               NaN               NaN              NaN

                                               Ghi chú
0    Đường Cấp IV miền núi, Mặt đường Bê tông nhựa,...
1    Đường Cấp V miền núi, Mặt đường Bê tông nhựa, ...
2    Đường Cấp V miền núi, Mặt đường Bê tông xi măn...
3    Đường Cấp V miền núi, Mặt đường Bê tông nhựa, ...
4    Đường Cấp V miền núi, Mặt đường Láng nhựa, bề ...
..                                                 ...
202  Đường cấp III Miền Núi, mặt đường Bê tông nhựa...
203  Đường cấp III Miền Núi, mặt đường Bê tông nhựa...
204  Đường cấp III Miền Núi, mặt đường Bê tông nhựa...
205  Đường cấp IV miền núi, mặt đường Bê tông XM, b...
206  Đường cấp V miền núi, mặt đường láng nhựa, bề ...

[207 rows x 14 columns]>

In [22]:
# JOIN
df = df_doan.merge(
    df_tuyen[['Ma_tuyen','Cap_quan_ly']],
    on='Ma_tuyen'
)
df

,Mã đoạn,Ma_tuyen,Cap_duong,ly_trinh_dau,ly_trinh_cuoi,Tình trạng,chieu_dai_thuc_te,Mã kết cấu mặt,Rộng mặt min (m),Rộng mặt max (m),Rộng nền min (m),Rộng nền max (m),Đơn vị bảo dưỡng,Ghi chú,Cap_quan_ly
0,QL4-01,QL4,IV,190.0,194.000,Tốt,4.00,BTN,10.5,10.5,NaN,NaN,Công ty …,"Đường Cấp IV miền núi, Mặt đường Bê tông nhựa,...",QL
1,QL4-02,QL4,V,194.0,250.800,Tốt,56.80,BTN,6.5,7.5,NaN,NaN,NaN,"Đường Cấp V miền núi, Mặt đường Bê tông nhựa, ...",QL
2,QL4-03,QL4,V,250.8,255.000,Tốt,4.20,BTN,5.0,5.0,NaN,NaN,NaN,"Đường Cấp V miền núi, Mặt đường Bê tông xi măn...",QL
3,QL4-04,QL4,V,255.0,272.000,Tốt,17.00,BTN,6.5,7.5,NaN,NaN,NaN,"Đường Cấp V miền núi, Mặt đường Bê tông nhựa, ...",QL
4,QL4-05,QL4,V,272.0,286.400,Tốt,14.40,LN,6.5,6.5,NaN,NaN,NaN,"Đường Cấp V miền núi, Mặt đường Láng nhựa, bề ...",QL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202,DX11-02,DX11,III,7.6,12.200,NaN,4.60,NaN,21.0,21.0,NaN,NaN,NaN,"Đường cấp III Miền Núi, mặt đường Bê tông nhựa...",DX
203,DX11-03,DX11,III,0.0,2.000,NaN,2.00,NaN,21.0,21.0,NaN,NaN,NaN,"Đường cấp III Miền Núi, mặt đường Bê tông nhựa...",DX
204,DX11-04,DX11,III,0.0,2.030,NaN,2.00,NaN,21.0,21.0,NaN,NaN,NaN,"Đường cấp III Miền Núi, mặt đường Bê tông nhựa...",DX
205,DX12-01,DX12,IV,0.0,49.117,NaN,45.81,NaN,5.0,5.0,NaN,NaN,NaN,"Đường cấp IV miền núi, mặt đường Bê tông XM, b...",DX
206,DX13-01,DX13,NaN,0.0,7.510,NaN,7.51,NaN,5.5,7.0,NaN,NaN,NaN,"Đường cấp V miền núi, mặt đường láng nhựa, bề ...",DX

In [23]:

df = df.merge(
    df_cap_ql.rename(columns={
        'ma_cap':'Cap_quan_ly',
        'ten_cap':'ten_cap_quan_ly',
        'thu_tu_hien_thi':'thu_tu_ql'
    }),
    on='Cap_quan_ly'
)
df

,Mã đoạn,Ma_tuyen,Cap_duong,ly_trinh_dau,ly_trinh_cuoi,Tình trạng,chieu_dai_thuc_te,Mã kết cấu mặt,Rộng mặt min (m),Rộng mặt max (m),Rộng nền min (m),Rộng nền max (m),Đơn vị bảo dưỡng,Ghi chú,Cap_quan_ly,ten_cap_quan_ly,mo_ta,thu_tu_ql
0,QL4-01,QL4,IV,190.0,194.000,Tốt,4.00,BTN,10.5,10.5,NaN,NaN,Công ty …,"Đường Cấp IV miền núi, Mặt đường Bê tông nhựa,...",QL,Đường quốc lộ,UBND tỉnh quản lý,2
1,QL4-02,QL4,V,194.0,250.800,Tốt,56.80,BTN,6.5,7.5,NaN,NaN,NaN,"Đường Cấp V miền núi, Mặt đường Bê tông nhựa, ...",QL,Đường quốc lộ,UBND tỉnh quản lý,2
2,QL4-03,QL4,V,250.8,255.000,Tốt,4.20,BTN,5.0,5.0,NaN,NaN,NaN,"Đường Cấp V miền núi, Mặt đường Bê tông xi măn...",QL,Đường quốc lộ,UBND tỉnh quản lý,2
3,QL4-04,QL4,V,255.0,272.000,Tốt,17.00,BTN,6.5,7.5,NaN,NaN,NaN,"Đường Cấp V miền núi, Mặt đường Bê tông nhựa, ...",QL,Đường quốc lộ,UBND tỉnh quản lý,2
4,QL4-05,QL4,V,272.0,286.400,Tốt,14.40,LN,6.5,6.5,NaN,NaN,NaN,"Đường Cấp V miền núi, Mặt đường Láng nhựa, bề ...",QL,Đường quốc lộ,UBND tỉnh quản lý,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202,DX11-02,DX11,III,7.6,12.200,NaN,4.60,NaN,21.0,21.0,NaN,NaN,NaN,"Đường cấp III Miền Núi, mặt đường Bê tông nhựa...",DX,Đường xã,"Xã, phường quản lý",5
203,DX11-03,DX11,III,0.0,2.000,NaN,2.00,NaN,21.0,21.0,NaN,NaN,NaN,"Đường cấp III Miền Núi, mặt đường Bê tông nhựa...",DX,Đường xã,"Xã, phường quản lý",5
204,DX11-04,DX11,III,0.0,2.030,NaN,2.00,NaN,21.0,21.0,NaN,NaN,NaN,"Đường cấp III Miền Núi, mặt đường Bê tông nhựa...",DX,Đường xã,"Xã, phường quản lý",5
205,DX12-01,DX12,IV,0.0,49.117,NaN,45.81,NaN,5.0,5.0,NaN,NaN,NaN,"Đường cấp IV miền núi, mặt đường Bê tông XM, b...",DX,Đường xã,"Xã, phường quản lý",5
206,DX13-01,DX13,NaN,0.0,7.510,NaN,7.51,NaN,5.5,7.0,NaN,NaN,NaN,"Đường cấp V miền núi, mặt đường láng nhựa, bề ...",DX,Đường xã,"Xã, phường quản lý",5

In [24]:

df = df.merge(
    df_cap_duong.rename(columns={
        'Ma_cap':'Cap_duong',
        'ten_cap':'ten_cap_ky_thuat',
        'thu_tu_hien_thi':'thu_tu_cd'
    }),
    on='Cap_duong'
)
df.head

<bound method NDFrame.head of      Mã đoạn Ma_tuyen Cap_duong  ly_trinh_dau  ly_trinh_cuoi Tình trạng  \
0     QL4-01      QL4        IV         190.0        194.000        Tốt
1     QL4-02      QL4         V         194.0        250.800        Tốt
2     QL4-03      QL4         V         250.8        255.000        Tốt
3     QL4-04      QL4         V         255.0        272.000        Tốt
4     QL4-05      QL4         V         272.0        286.400        Tốt
..       ...      ...       ...           ...            ...        ...
201  DX11-01     DX11       III           0.0          6.800        NaN
202  DX11-02     DX11       III           7.6         12.200        NaN
203  DX11-03     DX11       III           0.0          2.000        NaN
204  DX11-04     DX11       III           0.0          2.030        NaN
205  DX12-01     DX12        IV           0.0         49.117        NaN

     chieu_dai_thuc_te Mã kết cấu mặt  Rộng mặt min (m)  Rộng mặt max (m)  \
0                 4.00            BTN              10.5              10.5
1                56.80            BTN               6.5               7.5
2                 4.20            BTN               5.0               5.0
3                17.00            BTN               6.5               7.5
4                14.40             LN               6.5               6.5
..                 ...            ...               ...               ...
201               6.70            NaN              21.0              21.0
202               4.60            NaN              21.0              21.0
203               2.00            NaN              21.0              21.0
204               2.00            NaN              21.0              21.0
205              45.81            NaN               5.0               5.0

     ...  Rộng nền max (m)  Đơn vị bảo dưỡng  \
0    ...               NaN         Công ty …
1    ...               NaN               NaN
2    ...               NaN               NaN
3    ...               NaN               NaN
4    ...               NaN               NaN
..   ...               ...               ...
201  ...               NaN               NaN
202  ...               NaN               NaN
203  ...               NaN               NaN
204  ...               NaN               NaN
205  ...               NaN               NaN

                                               Ghi chú Cap_quan_ly  \
0    Đường Cấp IV miền núi, Mặt đường Bê tông nhựa,...          QL
1    Đường Cấp V miền núi, Mặt đường Bê tông nhựa, ...          QL
2    Đường Cấp V miền núi, Mặt đường Bê tông xi măn...          QL
3    Đường Cấp V miền núi, Mặt đường Bê tông nhựa, ...          QL
4    Đường Cấp V miền núi, Mặt đường Láng nhựa, bề ...          QL
..                                                 ...         ...
201  Đường cấp III Miền Núi, mặt đường Bê tông nhựa...          DX
202  Đường cấp III Miền Núi, mặt đường Bê tông nhựa...          DX
203  Đường cấp III Miền Núi, mặt đường Bê tông nhựa...          DX
204  Đường cấp III Miền Núi, mặt đường Bê tông nhựa...          DX
205  Đường cấp IV miền núi, mặt đường Bê tông XM, b...          DX

    ten_cap_quan_ly             mo_ta_x thu_tu_ql  ten_cap_ky_thuat  \
0     Đường quốc lộ   UBND tỉnh quản lý         2            Cấp IV
1     Đường quốc lộ   UBND tỉnh quản lý         2             Cấp V
2     Đường quốc lộ   UBND tỉnh quản lý         2             Cấp V
3     Đường quốc lộ   UBND tỉnh quản lý         2             Cấp V
4     Đường quốc lộ   UBND tỉnh quản lý         2             Cấp V
..              ...                 ...       ...               ...
201        Đường xã  Xã, phường quản lý         5           Cấp III
202        Đường xã  Xã, phường quản lý         5           Cấp III
203        Đường xã  Xã, phường quản lý         5           Cấp III
204        Đường xã  Xã, phường quản lý         5           Cấp III
205        Đường xã  Xã, phường quản lý         5            Cấp IV

                      mo_ta_y thu_tu_cd
0     Đường cấp IV - Miền núi         4
1      Đường cấp V - Miền núi         5
2      Đường cấp V - Miền núi         5
3      Đường cấp V - Miền núi         5
4      Đường cấp V - Miền núi         5
..                        ...       ...
201  Đường cấp III - Miền núi         3
202  Đường cấp III - Miền núi         3
203  Đường cấp III - Miền núi         3
204  Đường cấp III - Miền núi         3
205   Đường cấp IV - Miền núi         4

[206 rows x 21 columns]>

In [25]:

# Tính chiều dài
df['chieu_dai'] = df['chieu_dai_thuc_te'].fillna(
    df['ly_trinh_cuoi'] - df['ly_trinh_dau']
)

In [26]:

# Group
ketqua = df.groupby(
    ['Cap_quan_ly','ten_cap_quan_ly','thu_tu_ql',
     'Cap_duong','ten_cap_ky_thuat','thu_tu_cd'],
    as_index=False
)['chieu_dai'].sum()
ketqua
print(type(ketqua))

<class 'pandas.core.frame.DataFrame'>

In [27]:

# Sort
ketqua = ketqua.sort_values(['thu_tu_ql','thu_tu_cd'])

print(ketqua)

   Cap_quan_ly ten_cap_quan_ly  thu_tu_ql Cap_duong ten_cap_ky_thuat  \
8           QL   Đường quốc lộ          2       III          Cấp III
9           QL   Đường quốc lộ          2        IV           Cấp IV
10          QL   Đường quốc lộ          2         V            Cấp V
0           DT      Đường tỉnh          3       III          Cấp III
1           DT      Đường tỉnh          3        IV           Cấp IV
3           DT      Đường tỉnh          3         V            Cấp V
4           DT      Đường tỉnh          3        VI           Cấp VI
2           DT      Đường tỉnh          3        NO     Chưa vào cấp
5           DX        Đường xã          5       III          Cấp III
6           DX        Đường xã          5        IV           Cấp IV
7           DX        Đường xã          5         V            Cấp V

    thu_tu_cd  chieu_dai
8           3    123.154
9           4    495.150
10          5    325.010
0           3     60.887
1           4    330.873
3           5    451.767
4           6     49.500
2           7    546.939
5           3     43.790
6           4     93.799
7           5      8.000